# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Maximum likelihood estimation for beta distribution
#'
#' Estimates a beta-distribution by maximum likelihood, with pre-formatted
#' inputs for efficiency.
#'
#' @param tol tolerance for stopping (small positive number).
#' @param max_it maximum number of iterations in Newton method.
#' @param sly1 sum of log-observations.
#' @param sly2 sum of logs of 1 minus the observations.
#' @param sy sum of observations.
#' @param sy2 of squared observations.
#' @param n sample size.
#'
#' @details
#' Estimation is performed with a Newton method and the moment matching
#' estimators as starting values. Estimated parameters below 0.001 or above 100
#' are truncated for stability.
#'
#' This function is intended for internal use only.
#'
#' @return
#' NumericVector containing the parameters of the beta distribution.
#'
#' @author
#' Code is ported to Rcpp from the Rfast package (beta.mle) by Alexander Henzi.
#'
#' @keywords internal
NULL

#' Compute e-values based on beta distrbution
#'
#' Sequentially estimate a beta distribution and evaluate the density at the
#' next point in the sample.
#'
#' @param z numbers in (0,1), should not be equal to 0 or 1.
#' @param tol tolerance for stopping (small positive number).
#' @param max_it maximum number of iterations in Newton method.
#' @param n0 starting sample sizes. The first \code{n0} observations are
#'    used only for estimation and the e-values are not computed.
#'
#' @details
#' This function is intended for internal use only.
#'
#' @return
#' List containing the e-values (density evaluated at the given value of
#' \code{z[i]}) and a matrix of the parameters for each index \code{i}.
#'
#' @keywords internal
beta_e_cpp <- function(z, tol, max_it, n0) {
    .Call('_epit_beta_e_cpp', PACKAGE = 'epit', z, tol, max_it, n0)
}

